name: Generate Star Sports JSON

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JSON files
        run: |
          mkdir -p data output

          curl -s https://allinonereborn.online/jtv-fetch/jstr4web.json -o data/channels.json
          curl -s https://allinonereborn.online/jtv-fetch/jstarcookie/cookie.json -o data/cookies.json

      - name: Generate Star Sports JSON
        run: |
          mkdir -p output

          jq -n \
          --slurpfile cookies data/cookies.json \
          --slurpfile channels data/channels.json '
          
          def map_id($name):
            if $name == "Star Sports 1 Hindi HD" then "ss1h"
            elif $name == "Star Sports 1 HD" then "ss1"
            elif $name == "Star Sports 1 Tamil HD" then "ss1tam"
            elif $name == "Star Sports 1 Telugu HD" then "ss1tel"
            elif $name == "Star Sports 2 Hindi HD" then "ss2h"
            elif $name == "Star Sports 2 HD" then "ss2"
            elif $name == "Star Sports Select 1 HD" then "sss1h"
            elif $name == "Star Sports Select 2 HD" then "sss2h"
            elif $name == "Star Sports 1" then "ss1sd"
            elif $name == "Star Sports 2" then "ss2sd"
            elif $name == "Star Sports 3" then "ss3"
            else empty
            end;

          def get_cookie($name):
            ($cookies[0].failed_results[]
              | select(.channel_name == $name)
              | .error_details.final_url
              | capture("__hdnea__=(?<c>[^&]+)").c
            );

          $channels[0]
          | map(
              select(.name | test("Star Sports"))
              | select(map_id(.name) != null)
              | {
                  id: map_id(.name),
                  name: .name,
                  url: (.url | split("?")[0]),
                  cookie: ("__hdnea__=" + get_cookie(.name)),
                  keyId: .keyId,
                  key: .key,
                  logo: .logo
                }
            )
          ' > output/star_sports.json

      - name: Show output
        run: cat output/star_sports.json
